namespace MazeGame.Core;

/// <summary>
/// ===  YOUR CONTENT GOES HERE  ===
/// Add tiles and entities in the two methods below. Both the game and the level editor call
/// <see cref="RegisterAll"/> at start-up, so whatever you register shows up in the editor palette and in levels.
///
/// TILE      TileRegistry.Register(new TileDef("lava", "Lava") { Frames = new[] { "custom/lava_1.png", "custom/lava_2.png" }, Fps = 5, Deadly = true });
/// ENTITY    EntityRegistry.Register(new EntityType("slime", "Slime", (def, editor) => new Slime(def)) { Texture = "custom/slime.png" });
///
/// Images are .png or .svg files inside the assets folder. Level files then simply say "lava" or { "type": "slime" }.
/// </summary>
public static class GameContent
{
    private static bool _done;

    public static void RegisterAll()
    {
        if (_done) return;
        _done = true;
        RegisterTiles();
        RegisterTilesets();
        RegisterEntities();
        RegisterOverworldTiles();
    }

    private static void RegisterTiles()
    {
        // Shape: "" walk through, "#" solid, "=" one-way platform, "L" ladder
        TileRegistry.Register(new TileDef("lava", "Lava", shape: "", category: "Hazards")
        {
            Frames = new[] { "custom/lava_1.png", "custom/lava_2.png", "custom/lava_3.png" },   // animated tile
            Fps = 5,
            Deadly = true,                       // kills the player on touch
        });

        TileRegistry.Register(new TileDef("stone_brick", "Stone brick", shape: "#", category: "Custom blocks")
        {
            Texture = "custom/stone_brick.png",
        });

        TileRegistry.Register(new TileDef("gem_ruby", "Ruby", category: "Custom blocks")
        {
            Frames = new[] { "custom/ruby_1.png", "custom/ruby_2.png" },
            Fps = 3,
            GemValue = 25,                       // collectible, worth 25 coins
        });
    }

    // ---- three extra tilesets (art generated by tools/make_tilesets.py)

    private static void Solid(string id, string name, string cat, string tex)
        => TileRegistry.Register(new TileDef(id, name, shape: "#", category: cat) { Texture = $"custom/{tex}.png" });

    private static void Platform(string id, string name, string cat, string tex)
        => TileRegistry.Register(new TileDef(id, name, shape: "=", category: cat) { Texture = $"custom/{tex}.png" });

    private static void Decor(string id, string name, string cat, string tex, bool deadly = false)
        => TileRegistry.Register(new TileDef(id, name, shape: "", category: cat) { Texture = $"custom/{tex}.png", Deadly = deadly });

    private static void Gem(string id, string name, string cat, string prefix, int value)
        => TileRegistry.Register(new TileDef(id, name, category: cat)
        {
            Frames = new[] { $"custom/{prefix}_1.png", $"custom/{prefix}_2.png" },
            Fps = 3,
            GemValue = value,
        });

    private static void RegisterTilesets()
    {
        const string D = "Desert", S = "Snow & ice", C = "Castle";

        Solid("desert_sand", "Sand", D, "desert_sand");
        Solid("desert_sand_top", "Sand (top)", D, "desert_sand_top");
        Solid("desert_brick", "Sandstone brick", D, "desert_brick");
        Platform("desert_platform", "Sandstone platform", D, "desert_platform");
        Decor("desert_pillar", "Pillar", D, "desert_pillar");
        Decor("desert_cactus", "Cactus (hurts)", D, "desert_cactus", deadly: true);
        Gem("desert_gem", "Amber", D, "desert_gem", 10);

        Solid("snow_block", "Snow", S, "snow_block");
        Solid("ice_block", "Ice", S, "ice_block");
        Solid("snow_brick", "Snow brick", S, "snow_brick");
        Platform("snow_platform", "Snow platform", S, "snow_platform");
        Decor("snow_pine", "Snowy pine", S, "snow_pine");
        Decor("snow_icicle", "Icicles (hurt)", S, "snow_icicle", deadly: true);
        Gem("snow_gem", "Ice crystal", S, "snow_gem", 10);

        Solid("castle_brick", "Castle brick", C, "castle_brick");
        Solid("castle_dark", "Dark brick", C, "castle_dark");
        Platform("castle_platform", "Castle platform", C, "castle_platform");
        TileRegistry.Register(new TileDef("castle_ladder", "Castle ladder", shape: "L", category: C) { Texture = "custom/castle_ladder.png" });
        Decor("castle_bars", "Iron bars", C, "castle_bars");
        Decor("castle_spikes", "Spikes (hurt)", C, "castle_spikes", deadly: true);
        TileRegistry.Register(new TileDef("castle_torch", "Torch", shape: "", category: C)
        {
            Frames = new[] { "custom/castle_torch_1.png", "custom/castle_torch_2.png", "custom/castle_torch_3.png" },
            Fps = 6,
        });
        Gem("castle_gem", "Amethyst", C, "castle_gem", 10);
    }

    // ---- the overworld's own 2D tileset (art: tools/make_overworld_tiles.py, assets/overworld/)

    private static void Ow(string id, string name, string cat, bool walk = true, double speed = 1, int frames = 0)
        => OverworldTileRegistry.Register(new OverworldTileDef(id, name)
        {
            Category = cat,
            Walkable = walk,
            Speed = speed,
            Texture = $"overworld/{id}.png",
            Frames = frames > 0 ? Enumerable.Range(1, frames).Select(i => $"overworld/{id}_{i}.png").ToArray() : null,
            Fps = 2,
        });

    private static void RegisterOverworldTiles()
    {
        Ow("grass", "Grass", "Ground");
        Ow("flowers", "Flowers", "Ground");
        Ow("sand", "Sand", "Ground", speed: 0.85);
        Ow("snow", "Snow", "Ground", speed: 0.85);
        Ow("hills", "Hills", "Ground", speed: 0.7);
        Ow("path", "Dirt path", "Paths", speed: 1.15);
        Ow("road", "Stone road", "Paths", speed: 1.25);
        Ow("bridge", "Bridge", "Paths");
        Ow("forest", "Forest", "Obstacles", walk: false);
        Ow("pine_forest", "Snowy forest", "Obstacles", walk: false);
        Ow("mountain", "Mountain", "Obstacles", walk: false);
        Ow("water", "Water", "Water", walk: false, frames: 2);
        Ow("deep_water", "Deep water", "Water", walk: false, frames: 2);
        Ow("lava", "Lava", "Water", walk: false, frames: 2);
        Ow("town", "Town", "Places");
        Ow("castle", "Castle", "Places");
        Ow("cave", "Cave", "Places");
    }

    private static void RegisterEntities()
    {
        EntityRegistry.Register(
            new EntityType("slime", "Slime", (def, editor) => new Slime(def))
            {
                Texture = "custom/slime.png",
                Category = "Custom entities",
            }
            .Prop("direction", "Start direction (left / right)", "right"));

        EntityRegistry.Register(
            new EntityType("zone", "Script zone", (def, editor) => new Zone(def, editor))
            {
                Texture = "custom/zone.png",
                Category = "Logic",
            }
            .Prop("id", "Zone id (used by 'on enter \"id\"')", "zone1", PropKind.Text, true)
            .Prop("w", "Width in cells", "1", PropKind.Int)
            .Prop("h", "Height in cells", "1", PropKind.Int));

        EntityRegistry.Register(
            new EntityType("button", "Script button", (def, editor) => new ScriptButton(def))
            {
                Texture = "custom/button.png",
                Category = "Logic",
            }
            .Prop("id", "Button id (used by 'on use \"id\"')", "button1", PropKind.Text, true));
    }
}

/// <summary>
/// Example custom entity: a slime that walks like the original walkers (it hops up one-tile ledges and
/// turns at walls) and kills the player on touch.
/// </summary>
public sealed class Slime : Entity
{
    public Slime(EntityDef def)
    {
        Kind = EntityKind.Custom;
        PlaceInCell(def.X, def.Y, halfWidth: 13, halfHeight: 16);
        SizePct = 200;                                       // a 16x16 image drawn at 200% fills one cell
        Dir = def.Get("direction", "right").StartsWith("l", StringComparison.OrdinalIgnoreCase) ? -90 : 90;
    }

    public override void Update(World w)
    {
        if (Kind == EntityKind.Flip) { base.Update(w); return; }      // bumped from below: let the engine tumble it away
        StepWalker(w);                                                // gravity + walking + ledge hopping
        if (Kind == EntityKind.Flip) return;
        if (w.Mode == WorldMode.Playing && TouchesPlayer(w, 0.8)) w.KillPlayer();
    }
}


/// <summary>Invisible rectangle (visible in the editor) that fires the script events enter / exit / use.</summary>
public sealed class Zone : Entity
{
    private readonly string _id;
    private readonly double _hw, _hh;
    private bool _inside;

    public Zone(EntityDef def, bool editor)
    {
        Kind = EntityKind.Custom;
        _id = def.Get("id");
        int cw = Math.Max(1, def.GetInt("w", 1)), ch = Math.Max(1, def.GetInt("h", 1));
        _hw = cw * 16; _hh = ch * 16;
        Width = _hw; Height = _hh;
        X = def.X * 32 + _hw;
        Y = def.Y * 32 + _hh;
        SizePct = 200;
        Visible = editor;
    }

    public override void Update(World w)
    {
        if (w.Mode != WorldMode.Playing) return;
        bool now = TouchesPlayer(w, 1.0);
        if (now && !_inside) w.FireEvent("enter", _id);
        if (!now && _inside) w.FireEvent("exit", _id);
        if (now && w.Input.UsePressed) w.FireEvent("use", _id);
        _inside = now;
    }
}

/// <summary>A visible object the player activates with the use key; fires the script event "use".</summary>
public sealed class ScriptButton : Entity
{
    private readonly string _id;

    public ScriptButton(EntityDef def)
    {
        Kind = EntityKind.Custom;
        _id = def.Get("id");
        PlaceInCell(def.X, def.Y, halfWidth: 12, halfHeight: 12);
        SizePct = 200;
    }

    public override void Update(World w)
    {
        if (w.Mode == WorldMode.Playing && TouchesPlayer(w, 1.0) && w.Input.UsePressed)
        {
            w.PlaySound("pop");
            w.FireEvent("use", _id);
        }
    }
}
