#!/usr/bin/env python3
"""Generates src/MazeGame.Core/Generated/BuiltinTiles.g.cs: string ids for the original 79 tiles.

Reads tools/tile_tables.json (shape/group/keymap/recipe lists from the Scratch project) and the costume
names in assets/manifest.json.  Run:  python3 tools/tile_ids.py
Also importable: tile_ids.id_map() -> {tile number: string id}
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SEMANTIC = {1: 'blank', 2: 'air', 9: 'block_gold', 10: 'block_wood', 20: 'conveyor_left', 21: 'conveyor_right',
            22: 'ladder_top', 23: 'ladder', 24: 'gem_1', 25: 'gem_2', 26: 'gem_3', 27: 'gem_4', 28: 'player_spawn',
            29: 'walker', 30: 'danger', 31: 'bush', 32: 'cloud', 46: 'npc', 47: 'end_box', 68: 'piranha',
            74: 'logic_auto', 75: 'cloud_solid', 76: 'logic_death', 77: 'door', 78: 'pipe', 79: 'door_wide'}
ENTITY = {29: 'walker', 30: 'danger', 46: 'npc', 47: 'end_box', 68: 'piranha', 77: 'door', 78: 'pipe', 79: 'door_wide'}
EDITOR_ONLY = {1, 28, 74, 76}
GEM = {24: 1, 25: 2, 26: 5, 27: 10}
CATEGORY = {'1': 'Wood & pipes', '2': 'Blocks, ladders, clouds', '3': 'Orange blocks', '5': 'Grass & slopes',
            '6': 'Edge tiles', '4': 'Gems & player spawn', '9': 'Entities', '8': 'Doors, pipes & logic', '': 'Other'}


def slug(name):
    s = re.sub(r'([a-zA-Z])(\d)', r'\1_\2', name)
    s = re.sub(r'[^a-zA-Z0-9]+', '_', s).strip('_').lower()
    return s


def names():
    m = json.load(open(os.path.join(ROOT, 'assets/manifest.json')))['tiles']
    return {int(k): v['name'] for k, v in m.items()}


def id_map():
    nm = names()
    out, used = {}, set()
    for n in range(1, 80):
        i = SEMANTIC.get(n) or slug(nm[n])
        assert i not in used, (n, i)
        used.add(i)
        out[n] = i
    return out


def cs(x):
    return '"%s"' % str(x).replace('\\', '\\\\').replace('"', '\\"')


if __name__ == '__main__':
    t = json.load(open(os.path.join(ROOT, 'tools/tile_tables.json')))
    nm, ids = names(), id_map()
    get = lambda k, n: t[k][n] if n < len(t[k]) else ''
    # editor palette order: category order as the old palette, spawn marker last in its section
    out = ['// <auto-generated> by tools/tile_ids.py from the original Scratch project. Do not edit. </auto-generated>',
           'namespace MazeGame.Core;', '', 'internal static class BuiltinTiles', '{',
           '    internal static void Register()', '    {']
    order = ['1', '2', '3', '5', '6', '4', '9', '8', '']
    rows = []
    for n in range(1, 80):
        km = get('Keymap', n)
        rows.append((n, km))
    for n, km in rows:
        ent = ENTITY.get(n)
        flags = []
        if n in EDITOR_ONLY: flags.append('EditorOnly = true')
        if n in GEM: flags.append('GemValue = %d' % GEM[n])
        if n == 76: flags.append('Deadly = true')
        if ent: flags.append('Entity = %s' % cs(ent))
        extra = (', ' + ', '.join(flags)) if flags else ''
        out.append('        Add(%d, %s, %s, %s, %s, %s, %s, %s%s);' % (
            n, cs(ids[n]), cs(nm[n]), cs(get('Shape', n)), cs(get('Group', n)), cs(get('Recipes', n)),
            cs(CATEGORY.get(km, 'Other')), cs(km) if False else '0', ''))
    # NOTE: flags are applied through the helper below (kept simple: one statement per tile)
    out = out[:7]
    for n, km in rows:
        ent = ENTITY.get(n)
        props = []
        if n in EDITOR_ONLY: props.append('EditorOnly = true')
        if n in GEM: props.append('GemValue = %d' % GEM[n])
        if n == 76: props.append("CatchesDeath = true")
        if ent: props.append('Entity = %s' % cs(ent))
        init = (' { %s }' % ', '.join(props)) if props else ''
        out.append('        Add(new TileDef(%s, %s, %s, %s, %s, %s)%s, %d);' % (
            cs(ids[n]), cs(nm[n]), cs(get('Shape', n)), cs(get('Group', n)), cs(get('Recipes', n)),
            cs(CATEGORY.get(km, 'Other')), init, n))
    out += ['    }', '', '    private static void Add(TileDef def, int num) => TileRegistry.RegisterBuiltin(def, num);', '}', '']
    p = os.path.join(ROOT, 'src/MazeGame.Core/Generated/BuiltinTiles.g.cs')
    open(p, 'w').write('\n'.join(out))
    print('wrote', p, len(ids), 'tiles')
